#!/usr/bin/env bash

function signer.privkey()
{
  umask 027
  [[ -d ~/.signer ]] || mkdir -pv ~/.signer
  openssl ecparam -out ~/.signer/privkey.pem -name prime256v1 -genkey
  l ~/.signer
  umask 022
}

function signer.pubkey()
{
  umask 027
  [[ -f ~/.signer/privkey.pem ]] || signer.privkey && signer.pubkey
  openssl ec -in ~/.signer/privkey.pem -pubout -out ~/.signer/pubkey.pem
  l ~/.signer
  umask 022
}

function signer.sign()
{
 [[ ! $1 ]] && echo "No digest type provided. Exiting..."
 [[ ! -f ${2} ]] && echo "No file found. Exiting..."
 local dgst=${1}
 local data=${2}
 openssl dgst -${dgst} -sign ~/.signer/privkey.pem -out ${data}.${dgst} ${data}
 l ./${data}.${dgst}
 [[ $- != *i* ]] && return
 [[ -x /usr/bin/hastyhex ]] && hastyhex ./${data}.${dgst}
}

function signer.verify()
{
  [[ ! $1 ]] && echo "No digest type provided. Exiting..."
  [[ ! -f ${2} ]] && echo "No file found. Exiting..."
  local dgst=${1}
  local data=${2}
  echo -n "${data} -> "
  openssl dgst -${dgst} -verify ~/.signer/pubkey.pem -signature ./${data}.${dgst} ${data}
}

function signer.sign.sha1()
{
  local dgst=${FUNCNAME##*.}
  signer.sign ${dgst} ${1} || echo "Critical error occured while signing..."
}

function signer.verify.sha1()
{
  local dgst=${FUNCNAME##*.}
  signer.verify ${dgst} ${1} || echo "Critical error occured while verifying..."
}



